"""empty message

Revision ID: 4e2a4ae79219
Revises: 
Create Date: 2024-07-29 00:32:15.213574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2a4ae79219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.drop_column('layout')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
