"""empty message

Revision ID: e617fc028259
Revises: 
Create Date: 2024-09-10 14:57:48.154156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e617fc028259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_full_walkthrough', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('room_size')
        batch_op.drop_column('room_frequency_of_use')
        batch_op.drop_column('room_flooring_type')
        batch_op.drop_column('room_dirtiness_level')
        batch_op.drop_column('room_tools_supplies_on_hand')
        batch_op.drop_column('room_tools_supplies_required')
        batch_op.drop_column('room_windows')
        batch_op.drop_column('room_importance')
        batch_op.drop_column('room_function')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_function', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('room_importance', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('room_windows', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('room_tools_supplies_required', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('room_tools_supplies_on_hand', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('room_dirtiness_level', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('room_flooring_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('room_frequency_of_use', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('room_size', sa.FLOAT(), nullable=False))

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.drop_column('last_full_walkthrough')

    # ### end Alembic commands ###
