"""empty message

Revision ID: ec00b455a593
Revises: e617fc028259
Create Date: 2024-09-12 15:36:59.183444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec00b455a593'
down_revision = 'e617fc028259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_type', sa.String(length=80), nullable=False))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_due_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('task_due_time')
        batch_op.drop_column('task_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('task_due_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('task_due_date')

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.drop_column('home_type')

    # ### end Alembic commands ###
