"""empty message

Revision ID: fb7277b4e773
Revises: 4e2a4ae79219
Create Date: 2024-07-29 14:47:04.810453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7277b4e773'
down_revision = '4e2a4ae79219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('task_due_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('task_priority',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('task_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('task_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('task_scheduled_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('task_scheduled_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('task_tags',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('task_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('task_priority',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('task_due_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
